// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOivaOY-6D53kr26dDx61oxo9bwCOpkYo',
    appId: '1:528060880156:web:66ef438d2f147c7c4356d9',
    messagingSenderId: '528060880156',
    projectId: 'scheduler-43dbe',
    authDomain: 'scheduler-43dbe.firebaseapp.com',
    storageBucket: 'scheduler-43dbe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMAUXgqQkQ6cUNDuejIB6jtgoYcNddS60',
    appId: '1:528060880156:android:4ccc2633e484c12b4356d9',
    messagingSenderId: '528060880156',
    projectId: 'scheduler-43dbe',
    storageBucket: 'scheduler-43dbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2iDJ4t0YexKMUbx6_cc6V5k80dCFO6nY',
    appId: '1:528060880156:ios:cc5bf4aa168cf7d64356d9',
    messagingSenderId: '528060880156',
    projectId: 'scheduler-43dbe',
    storageBucket: 'scheduler-43dbe.appspot.com',
    iosClientId: '528060880156-3lhqbskek2j6rh8lpbnadnu183n06r7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.termProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2iDJ4t0YexKMUbx6_cc6V5k80dCFO6nY',
    appId: '1:528060880156:ios:cc5bf4aa168cf7d64356d9',
    messagingSenderId: '528060880156',
    projectId: 'scheduler-43dbe',
    storageBucket: 'scheduler-43dbe.appspot.com',
    iosClientId: '528060880156-3lhqbskek2j6rh8lpbnadnu183n06r7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.termProject',
  );
}
